spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "file:///C://Users//miste//OneDrive//Documents//microservices//zzsection6//v2-spring-cloud-config//config"
        #search-locations: "classpath:/config"

server:
  port: 8071